### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'dim'

### ISSUE THREAD

**Issue by ttttttty999** [chuxuzhang/KDD2019_HetGNN#11]
When i run HetGNN.py, the code raised this error:
Traceback (most recent call last):
 File "HetGNN.py", line 124, in <module>
    model_object = model_class(args)
  File "HetGNN.py", line 52, in \_\_init\_\_
    a_train_id_list, p_train_id_list, v_train_id_list)
  File "/public/xgg/ty/KDD2019_HetGNN-master/code/tools.py", line 45, in \_\_init\_\_
    self.softmax = nn.Softmax(dim = 1)
TypeError: \_\_init\_\_() got an unexpected keyword argument 'dim'

**Comment by ttttttty999** [comment]
I've worked it out.
