### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../data/academic_test/p_p_citation_list.txt'

### ISSUE THREAD

**Issue by empty-id** [chuxuzhang/KDD2019_HetGNN#9]
Hi, could you help me?

When I run ```python HetGNN.py```, the code raises this error:

```
FileNotFoundError: [Errno 2] No such file or directory: '../data/academic_test/p_p_citation_list.txt'
```

**Comment by fansariadeh** [comment]
Same here! I got the error. Could you please help with this?

**Comment by fansariadeh** [comment]
> Hi, could you help me?
> 
> When I run `python HetGNN.py`, the code raises this error:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '../data/academic_test/p_p_citation_list.txt'
> ```

change the nade of file academic to academic_test

**Comment by empty-id** [comment]
However, for testing, I find for node classification task, only node embedding is available instead of the whole model. Is there a completed training-testing pipeline?

**Comment by LiSu935** [comment]
> Hi, could you help me?
> 
> When I run `python HetGNN.py`, the code raises this error:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '../data/academic_test/p_p_citation_list.txt'
> ```

see readme file 'test data link' and download it there.

**Comment by ttttttty999** [comment]
When I run python HetGNN.py, the code raises this error:

> Traceback (most recent call last):
  File "HetGNN.py", line 124, in <module>
    model_object = model_class(args)
  File "HetGNN.py", line 52, in __init__
    a_train_id_list, p_train_id_list, v_train_id_list)
  File "/public/xgg/ty/KDD2019_HetGNN-master/code/tools.py", line 45, in __init__
    self.softmax = nn.Softmax(dim = 1)
TypeError: __init__() got an unexpected keyword argument 'dim'

**Comment by fansariadeh** [comment]
> However, for testing, I find for node classification task, only node embedding is available instead of the whole model. Is there a completed training-testing pipeline?

I actually am working on this code and have no idea how to feed the academic_test dataset into the code.
